apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - name: account
      mountPath: "/usr/share/nginx/html"
      readOnly: true
  volumes:
  - name: account
    secret:
      secretName: account
---    
apiVersion: v1
kind: Secret
metadata:
  name: account
type: Opaque
data:
  index.html: YWNjb3VudA==