apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-server
  name: web-svc
  namespace: default
spec:
  ports:
  - port: 5566
    protocol: TCP
    targetPort: 80
  selector:
    web: server
  sessionAffinity: None
  type: NodePort
  
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: default
  labels:
    web: server
spec:
  containers:
  - image: nginxdemos/hello
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
