apiVersion: v1
kind: Service
metadata:
  labels:
    web: server
  name: web-svc
  namespace: default
spec:
  ports:
  - port: 5566
    protocol: TCP
    targetPort: 80
  selector:
    web: server
  sessionAffinity: None
  type: NodePort
