apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: default
  labels:
    web: server
spec:
  containers:
  - image: nginxdemos/hello
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP